# Generated by Django 5.0.3 on 2024-04-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cake_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='desc',
            new_name='description',
        ),
    ]
